name: "nakama-server"
description: "Nakama server configuration"
database:
  # address:
  #   - "postgres:localdb@postgres:5432/nakama" # Overridden by command-line flag in Dockerfile
logger:
  level: "WARN"
session:
  token_expiry_sec: 7200
runtime:
  js_entrypoint: "index.js"
  http_key: "production-http-key" # SHOULD BE OVERRIDDEN BY ENV VAR
socket:
  server_key: "production-server-key" # SHOULD BE OVERRIDDEN BY ENV VAR
cors:
  origins:
    - "*"
